name: Compilar APK de Espirometría
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar archivos del repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar herramientas necesarias
        run: |
          pip install flet
          pip install python-docx
          pip install requests

      - name: Configurar Java (Requerido para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar SDK de Android y Aceptar Licencias
        uses: android-actions/setup-android@v3

      - name: Crear Aplicación Android (.apk) sin preguntas
        run: |
          flet build apk --no-interactive

      - name: Guardar el instalador final
        uses: actions/upload-artifact@v4
        with:
          name: Aplicacion-Espirometria-APK
          path: build/apk/*.apk
